/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistuni.egcc.MateApp.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class VentanaMDI extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMDI
     */
    public VentanaMDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        ItemSalir = new javax.swing.JMenuItem();
        menuOperaciones = new javax.swing.JMenu();
        ItemFactorial = new javax.swing.JMenuItem();
        ItemMcdMcm = new javax.swing.JMenuItem();
        ItemFibonacci = new javax.swing.JMenuItem();
        ItemPrimo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Operaciones Matemáticas");

        menuArchivo.setMnemonic('f');
        menuArchivo.setText("Archivo");

        ItemSalir.setMnemonic('o');
        ItemSalir.setText("Salir");
        menuArchivo.add(ItemSalir);

        menuBar.add(menuArchivo);

        menuOperaciones.setMnemonic('e');
        menuOperaciones.setText("Operaciones");

        ItemFactorial.setMnemonic('t');
        ItemFactorial.setText("Factorial");
        ItemFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemFactorialActionPerformed(evt);
            }
        });
        menuOperaciones.add(ItemFactorial);

        ItemMcdMcm.setMnemonic('y');
        ItemMcdMcm.setText("MCD y MCM");
        ItemMcdMcm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemMcdMcmActionPerformed(evt);
            }
        });
        menuOperaciones.add(ItemMcdMcm);

        ItemFibonacci.setMnemonic('p');
        ItemFibonacci.setText("Fibonacci");
        ItemFibonacci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemFibonacciActionPerformed(evt);
            }
        });
        menuOperaciones.add(ItemFibonacci);

        ItemPrimo.setMnemonic('d');
        ItemPrimo.setText("Primo");
        ItemPrimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemPrimoActionPerformed(evt);
            }
        });
        menuOperaciones.add(ItemPrimo);

        menuBar.add(menuOperaciones);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemFactorialActionPerformed
       
        FactorialView fact = new FactorialView();  //crear el nuevo formulario
        boolean mostrar=true;

        for (int a=0;a<escritorio.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
             if( fact.getClass().isInstance(escritorio.getComponent(a)))
                { JOptionPane.showMessageDialog(rootPane, "No se puede abrir una ventana ya abierta");
                 mostrar=false;
             }
        }
        if(mostrar){ escritorio.add(fact);
                fact.setVisible(true);}
        
        
        
        
    }//GEN-LAST:event_ItemFactorialActionPerformed

    private void ItemMcdMcmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemMcdMcmActionPerformed
        // TODO add your handling code here:
       McdMcmView mc = new McdMcmView();  //crear el nuevo formulario
        boolean mostrar=true;

        for (int i=0;i<escritorio.getComponentCount();i++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
             if( mc.getClass().isInstance(escritorio.getComponent(i)))
                { JOptionPane.showMessageDialog(rootPane, "No se puede abrir una ventana ya abierta");
                 mostrar=false;
             }
        }
        if(mostrar){ escritorio.add(mc);
                mc.setVisible(true);}
        
    }//GEN-LAST:event_ItemMcdMcmActionPerformed

    private void ItemFibonacciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemFibonacciActionPerformed
        // TODO add your handling code here:
        FibonacciView fib = new FibonacciView();  //crear el nuevo formulario
        boolean mostrar=true;

        for (int i=0;i<escritorio.getComponentCount();i++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
             if( fib.getClass().isInstance(escritorio.getComponent(i)))
                { JOptionPane.showMessageDialog(rootPane, "No se puede abrir una ventana ya abierta");
                 mostrar=false;
             }
        }
        if(mostrar){ escritorio.add(fib);
                fib.setVisible(true);}
        
        
    }//GEN-LAST:event_ItemFibonacciActionPerformed

    private void ItemPrimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemPrimoActionPerformed
        // TODO add your handling code here:
        PrimoView prim = new PrimoView();  //crear el nuevo formulario
        boolean mostrar=true;

        for (int i=0;i<escritorio.getComponentCount();i++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
             if( prim.getClass().isInstance(escritorio.getComponent(i)))
                { JOptionPane.showMessageDialog(rootPane, "No se puede abrir una ventana ya abierta");
                 mostrar=false;
             }
        }
        if(mostrar){ escritorio.add(prim);
                prim.setVisible(true);}
    }//GEN-LAST:event_ItemPrimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemFactorial;
    private javax.swing.JMenuItem ItemFibonacci;
    private javax.swing.JMenuItem ItemMcdMcm;
    private javax.swing.JMenuItem ItemPrimo;
    private javax.swing.JMenuItem ItemSalir;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuOperaciones;
    // End of variables declaration//GEN-END:variables

}
